---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: app/_data/menus.yml
  label: Menus
  match: "**/*"
- type: heading
  label: Config
- type: document
  path: app/_data/header.yaml
  label: Header
  match: "**/*"
- type: document
  path: app/_data/meta.yaml
  label: Meta
  match: "**/*"
- type: document
  path: app/_data/footer.yaml
  label: Footer
  match: "**/*"
- type: heading
  label: Data
- type: document
  path: app/_data/assets.yaml
  label: Assets
- type: document
  path: app/_data/projects.yaml
  label: Projects
  match: "**/*"
- type: jekyll-pages
  label: Pages
  create: all
  templates:
  - root
upload_dir: app/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    -d _site
