title: Joshuadesir.life 
description: >-  
 Inform & Inspire.
 
icons: [ "57x57", "72x72", "76X76", "114x114", "120x120", "144x144", "152x152", "168x168", "180x180" ]

plugins: 
  - id: jekyll-menus
    repo: https://github.com/forestryio/jekyll-menus/