title: Joshuadesir.life
copyright:
  - text: "&copy; 2021 - 2022 Joshua Desir"
    href: /

  - text: Made w/ God.

description:
socials:
  - name: instagram
    username: desir.designs
    link: https://www.instagram.com/desir.designs
    icon:
      set: brands
      name: instagram

  - name: Behance
    username: desir.designs
    icon:
      set: fab brands
      name: behance

  - name: Etsy
    username: desir.designs
    icon:
      set: fab brands
      name: etsy

  - name: Ko-Fi
    username: desir.designs
    icon:
      set: fas solid
      name: coffee

  - name: Pinterest
    username: desir.designs
    icon: 
     set: fab brands
     name: pinterest

  - name: Facebook
    icon:
      set: brands
      name: facebook

icons:
  props:
    basePath: /assets/icons/
    ext: .png
  data:
    - 57x57
    - 72x72
    - 76x76
    - 114x114
    - 120x120
    - 144x144
    - 152x152
    - 180x180
